name: {{project_name.snakeCase()}}
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  go_router: ^13.2.0
  get_it: ^7.6.0
  rxdart: 0.26.0
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  get_storage: ^2.1.1
  http: ^1.1.0
  devicelocale: ^0.7.1
  awesome_snackbar_content: ^0.1.3
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^3.0.1
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  go_router_builder: ^2.2.2

flutter:
  uses-material-design: true
  assets:
    - assets/mocks/user/